### ISSUE TITLE
Unable to populate Weather results

### ISSUE THREAD

**Issue by NBarter94** [QuentinCurri/pixel-startpage#1]
I've populated the requested fields but can't get any response & it's stuck on Loading. 

I've tested my details via the API directly that i've inputted on the weather.js & this populates correctly as seen below 

![image](https://user-images.githubusercontent.com/87838458/126726467-4b377875-3dc4-4d33-8ef3-b6f4cd90be8d.png)

Unsure why your weather.js isn't producing the details when my file shows the same details OpenWeatherMap is happy with as seen above.

![image](https://user-images.githubusercontent.com/87838458/126726866-15ed37c3-e06b-4012-8213-ae16296484e8.png)

Trying to use it on https://cuntcil.online/ but no luck. After a bit of investigation Chrome states "Uncaught SyntaxError: Invalid or unexpected token" weather.js:4 which is the token line, I've tried creating multiple different API key's but they give me the same result. As mentioned previously when I go directly to the link I get the results so fault seems to be with your weather.js

**Comment by QuentinCurri** [comment]
There doesn't seem to be a weather.js file in your js folder unless it is hidden in the sources. Maybe that is the issue? I tried the code on a separate HTML document and it worked fine.

**Comment by NBarter94** [comment]
> There doesn't seem to be a weather.js file in your js folder unless it is hidden in the sources. Maybe that is the issue? I tried the code on a separate HTML document and it worked fine.

Definitely in the sources under the js directory as seen below...
![image](https://user-images.githubusercontent.com/87838458/126729504-ef58c37a-9e40-481b-9a7f-f6de545f5a67.png)

**Comment by QuentinCurri** [comment]
![image](https://user-images.githubusercontent.com/67937168/126730191-e6dc805c-a466-4535-9ad8-4756c8f87b07.png)
![image](https://user-images.githubusercontent.com/67937168/126730206-0dbec73d-8082-4deb-8b72-b380250cb08c.png)

Oh the problem is the token constant isn't a string. Surround ur Api token with single quotations ''

**Comment by NBarter94** [comment]
> ![image](https://user-images.githubusercontent.com/67937168/126730191-e6dc805c-a466-4535-9ad8-4756c8f87b07.png)
> ![image](https://user-images.githubusercontent.com/67937168/126730206-0dbec73d-8082-4deb-8b72-b380250cb08c.png)
> 
> Oh the problem is the token constant isn't a string. Surround ur Api token with single quotations ''

Bit odd that the weather.js is not appearing for you but I've now done that & it's working.... No idea why that didn't come to mind, thank you for the help 👍
